### ISSUE TITLE
Calendar does not load the birthday events

### ISSUE THREAD

**Issue by Starplayer84** [PalatinCoder/MMM-GoogleBirthdaysProvider#1]
Hi,
I´ve installed your Module on my Mirror and connected it witch the calendar module, but it does not load the events into the calendar. All the time it shows "loading".
In my googleaccount the API shows some traffic and if I start the Mirror in 'MagicMirror/config' with 'npm start' it says it´s connected and working.
Do you know this issue and how to solve it?

Greeting from Germany

![config entry](https://user-images.githubusercontent.com/45743084/49859432-d3628a00-fdf7-11e8-9eb3-7e2021ca1c75.PNG)

![start sequenz](https://user-images.githubusercontent.com/45743084/49859435-d65d7a80-fdf7-11e8-90ed-b507175a6b27.PNG)

**Comment by PalatinCoder** [comment]
Hi,
try accessing the feed with `http://` instead of `https://`. AFAIK the Magic Mirror only serves via http.
Also, you could try `wget http://localhost:8080/mmm-googlebirthdaysprovider` from the shell to see what the server returns.
Greetings back also from Germany :wink:

**Comment by Starplayer84** [comment]
Perfect, now everything works finde, thank you!
This module is really nice, great work! ;)

Greetings ausm Pott

**Comment by Starplayer84** [comment]
One more question, how do you just get the days till the Birthday?
My Mirror says: "in ... Days-00:00".
Is there a configuration for the calendar module i don´t know?

**Comment by PalatinCoder** [comment]
There are some [configuration options](https://github.com/MichMich/MagicMirror/tree/master/modules/default/calendar#configuration-options) like `timeFormat` and `getRelative` which control if and how dates are displayed as relative dates. But most likely the problem is something else. The calendar module uses some "heuristics" to decide if some event is a whole day or not (instead of simply relying on the "wholeDay" attribute of the VEVENT ...) I've faced this problem during development and so far I couldn't come up with a stable solution. I suspect that the generated start and end times are offset due to timezone issues. 
Could you provide a screenshot and an excerpt of the actual feed generated by the birthday provider? (You can get it with the wget command I mentioned above)

**Comment by Starplayer84** [comment]
I tried to chance these, but it does not solve the problem.
Sure here are the pictures:
![255411357_24852](https://user-images.githubusercontent.com/45743084/49880094-b051cd80-fe2b-11e8-9289-578a6e1ce95f.jpg)

![wget command](https://user-images.githubusercontent.com/45743084/49880099-b3e55480-fe2b-11e8-940f-23a17aa60d9e.PNG)

**Comment by PalatinCoder** [comment]
Closed due to inactivity, feel free to reopen if needed
