### ISSUE TITLE
symbol: "birthday-cake", color: '#f00'

### ISSUE THREAD

**Issue by Googinot** [PalatinCoder/MMM-GoogleBirthdaysProvider#27]
Hello. I can not figure out why the "🎂" does not change color. Tell me what I did wrong? thx!
![sim](https://user-images.githubusercontent.com/93269843/151195594-8bad5321-e18c-4b92-bed1-3b15cd07fd37.jpg)

**Comment by PalatinCoder** [comment]
The coloring of the entries is done by the calendar module and actually not related to this module. Please check the [documentation of the calendar module](https://docs.magicmirror.builders/modules/calendar.html#syncing-your-microsoft-google-and-apple-calendars). There have been some releases of MagicMirror since I wrote this module and the readme, and it seems one of them introduced a new parameter that needs to be set.
